///////////////////////////////////////////////////////////////////////
// Copyright (c) 2025 Owsap.
// All rights reserved.
//
// Email: admin@owsap.dev
// Web: https://owsap.dev/
//

#pragma once

#include <cstdint>
#include <map>
#include <string>

#include <length.h>

enum class ItemType
{
	ITEM_NONE,
	ITEM_WEAPON,
	ITEM_ARMOR,
	ITEM_USE,
	ITEM_AUTOUSE,
	ITEM_MATERIAL,
	ITEM_SPECIAL,
	ITEM_TOOL,
	ITEM_LOTTERY,
	ITEM_ELK,
	ITEM_METIN,
	ITEM_CONTAINER,
	ITEM_FISH,
	ITEM_ROD,
	ITEM_RESOURCE,
	ITEM_CAMPFIRE,
	ITEM_UNIQUE,
	ITEM_SKILLBOOK,
	ITEM_QUEST,
	ITEM_POLYMORPH,
	ITEM_TREASURE_BOX,
	ITEM_TREASURE_KEY,
	ITEM_SKILLFORGET,
	ITEM_GIFTBOX,
	ITEM_PICK,
	ITEM_HAIR,
	ITEM_TOTEM,
	ITEM_BLEND,
	ITEM_COSTUME,
	ITEM_DS,
	ITEM_SPECIAL_DS,
	ITEM_EXTRACT,
	ITEM_SECONDARY_COIN,
	ITEM_RING,
	ITEM_BELT,
	ITEM_PET,
	ITEM_MEDIUM,
	ITEM_GACHA,
	ITEM_PASSIVE,
	ITEM_MERCENARY,
	ITEM_ALCHEMY,
	ITEM_FORCE
};

enum class WeaponSubTypes
{
	WEAPON_SWORD,
	WEAPON_DAGGER,
	WEAPON_BOW,
	WEAPON_TWO_HANDED,
	WEAPON_BELL,
	WEAPON_FAN,
	WEAPON_ARROW,
	WEAPON_MOUNT_SPEAR,
	WEAPON_CLAW,
	WEAPON_QUIVER,
	WEAPON_BOUQUET,
	WEAPON_MAX_NUM
};

enum class ArmorSubTypes
{
	ARMOR_BODY,
	ARMOR_HEAD,
	ARMOR_SHIELD,
	ARMOR_WRIST,
	ARMOR_FOOTS,
	ARMOR_NECK,
	ARMOR_EAR,
	ARMOR_PENDANT,
	ARMOR_GLOVE
};

enum class UseSubTypes
{
	USE_POTION,
	USE_TALISMAN,
	USE_TUNING,
	USE_MOVE,
	USE_TREASURE_BOX,
	USE_MONEYBAG,
	USE_BAIT,
	USE_ABILITY_UP,
	USE_AFFECT,
	USE_CREATE_STONE,
	USE_SPECIAL,
	USE_POTION_NODELAY,
	USE_CLEAR,
	USE_INVISIBILITY,
	USE_DETACHMENT,
	USE_BUCKET,
	USE_POTION_CONTINUE,
	USE_CLEAN_SOCKET,
	USE_CHANGE_ATTRIBUTE,
	USE_ADD_ATTRIBUTE,
	USE_ADD_ACCESSORY_SOCKET,
	USE_PUT_INTO_ACCESSORY_SOCKET,
	USE_ADD_ATTRIBUTE2,
	USE_RECIPE,
	USE_CHANGE_ATTRIBUTE2,
	USE_BIND,
	USE_UNBIND,
	USE_TIME_CHARGE_PER,
	USE_TIME_CHARGE_FIX,
	USE_PUT_INTO_BELT_SOCKET,
	USE_PUT_INTO_RING_SOCKET,
	USE_CHANGE_COSTUME_ATTR,
	USE_RESET_COSTUME_ATTR,
	USE_UNK_33,
	USE_SELECT_ATTRIBUTE,
	USE_FLOWER,
	USE_EMOTION_PACK,
	USE_ELEMENT_UPGRADE,
	USE_ELEMENT_DOWNGRADE,
	USE_ELEMENT_CHANGE,
	USE_CALL,
	USE_POTION_TOWER,
	USE_POTION_NODELAY_TOWER,
	USE_REMOVE_AFFECT,
	USE_EMOTION_TOWER,
	USE_SECRET_DUNGEON_SCROLL,
	USE_MAP,
	USE_ADD_FOOTS_SOCKET,
	USE_SELECT_BOX,
	USE_TITLE
};

enum class AutoUseSubTypes
{
	AUTOUSE_POTION,
	AUTOUSE_ABILITY_UP,
	AUTOUSE_BOMB,
	AUTOUSE_GOLD,
	AUTOUSE_MONEYBAG,
	AUTOUSE_TREASURE_BOX
};

enum class MaterialSubTypes
{
	MATERIAL_LEATHER,
	MATERIAL_BLOOD,
	MATERIAL_ROOT,
	MATERIAL_NEEDLE,
	MATERIAL_JEWEL,
	MATERIAL_DS_REFINE_NORMAL,
	MATERIAL_DS_REFINE_BLESSED,
	MATERIAL_DS_REFINE_HOLLY,
	MATERIAL_DS_CHANGE_ATTR,
	MATERIAL_PASSIVE_WEAPON,
	MATERIAL_PASSIVE_ARMOR,
	MATERIAL_PASSIVE_ACCE,
	MATERIAL_PASSIVE_ELEMENT
};

enum class SpecialSubTypes
{
	SPECIAL_MAP,
	SPECIAL_KEY,
	SPECIAL_DOC,
	SPECIAL_SPIRIT
};

enum class ToolSubTypes
{
	TOOL_FISHING_ROD
};

enum class LotterySubTypes
{
	LOTTERY_TICKET,
	LOTTERY_INSTANT
};

enum class ElkSubTypes
{
};

enum class MetinSubTypes
{
	METIN_NORMAL,
	METIN_SUNGMA,
	METIN_ELEMENTAL
};

enum class ContainerSubTypes
{
};

enum class FishSubTypes
{
	FISH_ALIVE,
	FISH_DEAD
};

enum class RodSubTypes
{
};

enum class ResourceSubTypes
{
	RESOURCE_FISHBONE,
	RESOURCE_WATERSTONEPIECE,
	RESOURCE_WATERSTONE,
	RESOURCE_BLOOD_PEARL,
	RESOURCE_BLUE_PEARL,
	RESOURCE_WHITE_PEARL,
	RESOURCE_BUCKET,
	RESOURCE_CRYSTAL,
	RESOURCE_GEM,
	RESOURCE_STONE,
	RESOURCE_METIN,
	RESOURCE_ORE,
	RESOURCE_AURA
};

enum class CampfireSubTypes
{
};

enum class UniqueSubTypes
{
	UNIQUE_NONE,
	UNIQUE_BOOK,
	UNIQUE_SPECIAL_RIDE,
	UNIQUE_3,
	UNIQUE_4,
	UNIQUE_5,
	UNIQUE_6,
	UNIQUE_7,
	UNIQUE_8,
	UNIQUE_9,
	UNIQUE_BUNDLE
};

enum class SkillBookSubTypes
{
	SKILL_BOOK,
	SKILL_BOOK_HORSE
};

enum class QuestSubTypes
{
	QUEST_NONE,
	QUEST_PET_PAY,
	QUEST_WARP,
	QUEST_GEM_BAG
};

enum class PolymorphSubTypes
{
	POLYMORPH_NORMAL,
	POLYMORPH_SINGIGEON
};

enum class TreasureBoxSubTypes
{
};

enum class TreasureKeySubTypes
{
};

enum class SkillForgetSubTypes
{
};

enum class GiftBoxSubTypes
{
	GIFTBOX_ITEM,
	GIFTBOX_ENTITY
};

enum class PickSubTypes
{
};

enum class HairSubTypes
{
};

enum class TotemSubTypes
{
};

enum class BlendSubTypes
{
};

enum class CostumeSubTypes
{
	COSTUME_BODY,
	COSTUME_HAIR,
	COSTUME_MOUNT,
	COSTUME_ACCE,
	COSTUME_WEAPON,
	COSTUME_AURA,
	COSTUME_MOUNT_STANDING
};

enum class DragonSoulSubTypes
{
	DS_SLOT1,
	DS_SLOT2,
	DS_SLOT3,
	DS_SLOT4,
	DS_SLOT5,
	DS_SLOT6,
	DS_SLOT7
};

enum class SpecialDragonSoulSubTypes
{
};

enum class ExtractSubTypes
{
	EXTRACT_DRAGON_SOUL,
	EXTRACT_DRAGON_HEART
};

enum class SecondaryCoinSubTypes
{
};

enum class RingSubTypes
{
};

enum class BeltSubTypes
{
};

enum class PetSubTypes
{
	PET_EGG,
	PET_UPBRINGING,
	PET_BAG,
	PET_FEEDSTUFF,
	PET_SKILL,
	PET_SKILL_DEL_BOOK,
	PET_NAME_CHANGE,
	PET_EXPFOOD,
	PET_SKILL_ALL_DEL_BOOK,
	PET_EXPFOOD_PER,
	PET_ATTR_DETERMINE,
	PET_ATTR_CHANGE,
	PET_PAY,
	PET_PRIMIUM_FEEDSTUFF,
	PET_BATTLE_EXP_FOOD
};

enum class MediumSubTypes
{
	MEDIUM_MOVE_COSTUME_ATTR,
	MEDIUM_MOVE_ACCE_ATTR
};

enum class GachaSubTypes
{
	USE_GACHA,
	GEM_LUCKY_BOX_GACHA,
	SPECIAL_LUCKY_BOX_GACHA,
	SPECIAL_LUCKY_BOX_ROYAL_GACHA
};

enum class PassiveSubTypes
{
	PASSIVE_JOB
};

enum class MercenarySubTypes
{
	MERCENARY_0,
	MERCENARY_1,
	MERCENARY_2,
	MERCENARY_3,
	MERCENARY_4,
	MERCENARY_5,
	MERCENARY_6
};

enum class AlchemySubTypes
{
	ARMOR,
	WEAPON,
	ACCESSORY,
	BELT,
	EVENT,
	ETC,
	JOB,
	SETADD_WEAPON,
	SETADD_ARMOR_BODY,
	SETADD_ARMOR_HELMET,
	PET,
	SKILL_BOOK,
	GLOVE
};

enum class ForceSubTypes
{
	NORMAL_ATTACK_FORCE,
	SKILL_ATTACK_FORCE
};

////////////////////////////////////////////////////

enum class ItemAntiFlag
{
	ANTI_FEMALE = 0,
	ANTI_MALE = 1,
	ANTI_MUSA = 2,
	ANTI_ASSASSIN =3,
	ANTI_SURA = 4,
	ANTI_MUDANG = 5,
	ANTI_GET = 6,
	ANTI_DROP = 7,
	ANTI_SELL = 8,
	ANTI_EMPIRE_A = 9,
	ANTI_EMPIRE_B = 10,
	ANTI_EMPIRE_C = 11,
	ANTI_SAVE = 12,
	ANTI_GIVE = 13,
	ANTI_PKDROP = 14,
	ANTI_STACK = 15,
	ANTI_MYSHOP = 16,
	ANTI_SAFEBOX = 17,
	ANTI_WOLFMAN = 18,
	ANTI_RT_REMOVE = 19,
	ANTI_QUICKSLOT = 20,
	ANTI_CHANGELOOK = 21,
	ANTI_REINFORCE = 22,
	ANTI_ENCHANT = 23,
	ANTI_ENERGY = 24,
	ANTI_PETFEED = 25,
	ANTI_APPLY = 26,
	ANTI_ACCE = 27,
	ANTI_MAIL = 28,
};

enum class ItemFlag
{
	ITEM_TUNABLE = 0,
	ITEM_STACKABLE = 1,
	COUNT_PER_1GOLD = 2,
	ITEM_SLOW_QUERY = 3,
	ITEM_MAKECOUNT = 4,
	ITEM_IRREMOVABLE = 5,
	CONFIRM_WHEN_USE = 6,
	LOG = 7,
	ITEM_APPLICABLE = 8,
};

enum class ItemWearFlag
{
	WEAR_BODY = 0,
	WEAR_HEAD = 1,
	WEAR_FOOTS = 2,
	WEAR_WRIST = 3,
	WEAR_WEAPON = 4,
	WEAR_NECK = 5,
	WEAR_EAR = 6,
	WEAR_SHIELD = 7,
	WEAR_UNIQUE = 8,
	WEAR_ARROW = 9,
	WEAR_HAIR = 10,
	WEAR_ABILITY = 11,
	WEAR_PENDANT = 12,
	WEAR_GLOVE = 13
};

enum class ItemLimitType
{
	LIMIT_NONE,
	LEVEL,
	STR,
	DEX,
	INT,
	CON,
	REAL_TIME,
	REAL_TIME_FIRST_USE,
	TIMER_BASED_ON_WEAR,
	NEWWORLD_LEVEL,
	DURATION
};

enum ItemMaskTypes
{
	MASK_ITEM_TYPE_NONE,
	MASK_ITEM_TYPE_MOUNT_PET,
	MASK_ITEM_TYPE_EQUIPMENT_WEAPON,
	MASK_ITEM_TYPE_EQUIPMENT_ARMOR,
	MASK_ITEM_TYPE_EQUIPMENT_JEWELRY,
	MASK_ITEM_TYPE_TUNING,
	MASK_ITEM_TYPE_POTION,
	MASK_ITEM_TYPE_FISHING_PICK,
	MASK_ITEM_TYPE_DRAGON_STONE,
	MASK_ITEM_TYPE_COSTUMES,
	MASK_ITEM_TYPE_SKILL,
	MASK_ITEM_TYPE_UNIQUE,
	MASK_ITEM_TYPE_ETC,
	MASK_ITEM_TYPE_MAX
};

enum ItemMaskSubTypes
{
	MASK_ITEM_SUBTYPE_ARMOR_ARMOR_BODY = 0,
	MASK_ITEM_SUBTYPE_ARMOR_ARMOR_HEAD = 1,
	MASK_ITEM_SUBTYPE_ARMOR_ARMOR_SHIELD = 2,
	MASK_ITEM_SUBTYPE_ARMOR_ARMOR_GLOVE = 3,
	MASK_ITEM_SUBTYPE_COSTUMES_COSTUME_WEAPON = 0,
	MASK_ITEM_SUBTYPE_COSTUMES_COSTUME_BODY = 1,
	MASK_ITEM_SUBTYPE_COSTUMES_COSTUME_HAIR = 2,
	MASK_ITEM_SUBTYPE_COSTUMES_SASH = 3,
	MASK_ITEM_SUBTYPE_COSTUMES_ETC = 4,
	MASK_ITEM_SUBTYPE_COSTUMES_AURA = 5,
	MASK_ITEM_SUBTYPE_DRAGON_STONE_DRAGON_DIAMOND = 0,
	MASK_ITEM_SUBTYPE_DRAGON_STONE_DRAGON_RUBY = 1,
	MASK_ITEM_SUBTYPE_DRAGON_STONE_DRAGON_JADE = 2,
	MASK_ITEM_SUBTYPE_DRAGON_STONE_DRAGON_SAPPHIRE = 3,
	MASK_ITEM_SUBTYPE_DRAGON_STONE_DRAGON_GARNET = 4,
	MASK_ITEM_SUBTYPE_DRAGON_STONE_DRAGON_ONYX = 5,
	MASK_ITEM_SUBTYPE_DRAGON_STONE_DRAGON_DEMON = 6,
	MASK_ITEM_SUBTYPE_DRAGON_STONE_ETC = 7,
	MASK_ITEM_SUBTYPE_ETC_GIFTBOX = 0,
	MASK_ITEM_SUBTYPE_ETC_MATRIMORY = 1,
	MASK_ITEM_SUBTYPE_ETC_EVENT = 2,
	MASK_ITEM_SUBTYPE_ETC_SEAL = 3,
	MASK_ITEM_SUBTYPE_ETC_PARTI = 4,
	MASK_ITEM_SUBTYPE_ETC_POLYMORPH = 5,
	MASK_ITEM_SUBTYPE_ETC_RECIPE = 6,
	MASK_ITEM_SUBTYPE_ETC_ETC = 7,
	MASK_ITEM_SUBTYPE_FISHING_PICK_FISHING_POLE = 0,
	MASK_ITEM_SUBTYPE_FISHING_PICK_EQUIPMENT_PICK = 1,
	MASK_ITEM_SUBTYPE_FISHING_PICK_FOOD = 2,
	MASK_ITEM_SUBTYPE_FISHING_PICK_STONE = 3,
	MASK_ITEM_SUBTYPE_FISHING_PICK_ETC = 4,
	MASK_ITEM_SUBTYPE_JEWELRY_ARMOR_WRIST = 0,
	MASK_ITEM_SUBTYPE_JEWELRY_ARMOR_FOOTS = 1,
	MASK_ITEM_SUBTYPE_JEWELRY_ARMOR_NECK = 2,
	MASK_ITEM_SUBTYPE_JEWELRY_ARMOR_EAR = 3,
	MASK_ITEM_SUBTYPE_JEWELRY_ITEM_BELT = 4,
	MASK_ITEM_SUBTYPE_JEWELRY_ARMOR_PENDANT = 5,
	MASK_ITEM_SUBTYPE_MOUNT_PET_MOUNT = 0,
	MASK_ITEM_SUBTYPE_MOUNT_PET_CHARGED_PET = 1,
	MASK_ITEM_SUBTYPE_MOUNT_PET_FREE_PET = 2,
	MASK_ITEM_SUBTYPE_MOUNT_PET_EGG = 3,
	MASK_ITEM_SUBTYPE_POTION_ABILITY = 0,
	MASK_ITEM_SUBTYPE_POTION_HAIRDYE = 1,
	MASK_ITEM_SUBTYPE_POTION_ETC = 2,
	MASK_ITEM_SUBTYPE_SKILL_PAHAE = 0,
	MASK_ITEM_SUBTYPE_SKILL_SKILL_BOOK = 1,
	MASK_ITEM_SUBTYPE_SKILL_BOOK_OF_OBLIVION = 2,
	MASK_ITEM_SUBTYPE_SKILL_ETC = 3,
	MASK_ITEM_SUBTYPE_SKILL_SKILL_BOOK_HORSE = 4,
	MASK_ITEM_SUBTYPE_TUNING_RESOURCE = 0,
	MASK_ITEM_SUBTYPE_TUNING_STONE = 1,
	MASK_ITEM_SUBTYPE_TUNING_ETC = 2,
	MASK_ITEM_SUBTYPE_TUNING_ALCHEMY = 3,
	MASK_ITEM_SUBTYPE_UNIQUE_ABILITY = 0,
	MASK_ITEM_SUBTYPE_UNIQUE_ETC = 1,
	MASK_ITEM_SUBTYPE_WEAPON_WEAPON_SWORD = 0,
	MASK_ITEM_SUBTYPE_WEAPON_WEAPON_DAGGER = 1,
	MASK_ITEM_SUBTYPE_WEAPON_WEAPON_BOW = 2,
	MASK_ITEM_SUBTYPE_WEAPON_WEAPON_TWO_HANDED = 3,
	MASK_ITEM_SUBTYPE_WEAPON_WEAPON_BELL = 4,
	MASK_ITEM_SUBTYPE_WEAPON_WEAPON_CLAW = 5,
	MASK_ITEM_SUBTYPE_WEAPON_WEAPON_FAN = 6,
	MASK_ITEM_SUBTYPE_WEAPON_WEAPON_MOUNT_SPEAR = 7,
	MASK_ITEM_SUBTYPE_WEAPON_WEAPON_ARROW = 8
};

enum class ApplyType
{
	APPLY_NONE,
	APPLY_MAX_HP,
	APPLY_MAX_SP,
	APPLY_CON,
	APPLY_INT,
	APPLY_STR,
	APPLY_DEX,
	APPLY_ATT_SPEED,
	APPLY_MOV_SPEED,
	APPLY_CAST_SPEED,
	APPLY_HP_REGEN,
	APPLY_SP_REGEN,
	APPLY_POISON_PCT,
	APPLY_STUN_PCT,
	APPLY_SLOW_PCT,
	APPLY_CRITICAL_PCT,
	APPLY_PENETRATE_PCT,
	APPLY_ATTBONUS_HUMAN,
	APPLY_ATTBONUS_ANIMAL,
	APPLY_ATTBONUS_ORC,
	APPLY_ATTBONUS_MILGYO,
	APPLY_ATTBONUS_UNDEAD,
	APPLY_ATTBONUS_DEVIL,
	APPLY_STEAL_HP,
	APPLY_STEAL_SP,
	APPLY_MANA_BURN_PCT,
	APPLY_DAMAGE_SP_RECOVER,
	APPLY_BLOCK,
	APPLY_DODGE,
	APPLY_RESIST_SWORD,
	APPLY_RESIST_TWOHAND,
	APPLY_RESIST_DAGGER,
	APPLY_RESIST_BELL,
	APPLY_RESIST_FAN,
	APPLY_RESIST_BOW,
	APPLY_RESIST_FIRE,
	APPLY_RESIST_ELEC,
	APPLY_RESIST_MAGIC,
	APPLY_RESIST_WIND,
	APPLY_REFLECT_MELEE,
	APPLY_REFLECT_CURSE,
	APPLY_POISON_REDUCE,
	APPLY_KILL_SP_RECOVER,
	APPLY_EXP_DOUBLE_BONUS,
	APPLY_GOLD_DOUBLE_BONUS,
	APPLY_ITEM_DROP_BONUS,
	APPLY_POTION_BONUS,
	APPLY_KILL_HP_RECOVER,
	APPLY_IMMUNE_STUN,
	APPLY_IMMUNE_SLOW,
	APPLY_IMMUNE_FALL,
	APPLY_SKILL,
	APPLY_BOW_DISTANCE,
	APPLY_ATT_GRADE_BONUS,
	APPLY_DEF_GRADE_BONUS,
	APPLY_MAGIC_ATT_GRADE,
	APPLY_MAGIC_DEF_GRADE,
	APPLY_CURSE_PCT,
	APPLY_MAX_STAMINA,
	APPLY_ATTBONUS_WARRIOR,
	APPLY_ATTBONUS_ASSASSIN,
	APPLY_ATTBONUS_SURA,
	APPLY_ATTBONUS_SHAMAN,
	APPLY_ATTBONUS_MONSTER,
	APPLY_MALL_ATTBONUS,
	APPLY_MALL_DEFBONUS,
	APPLY_MALL_EXPBONUS,
	APPLY_MALL_ITEMBONUS,
	APPLY_MALL_GOLDBONUS,
	APPLY_MAX_HP_PCT,
	APPLY_MAX_SP_PCT,
	APPLY_SKILL_DAMAGE_BONUS,
	APPLY_NORMAL_HIT_DAMAGE_BONUS,
	APPLY_SKILL_DEFEND_BONUS,
	APPLY_NORMAL_HIT_DEFEND_BONUS,
	APPLY_PC_BANG_EXP_BONUS,
	APPLY_PC_BANG_DROP_BONUS,
	APPLY_EXTRACT_HP_PCT,
	APPLY_RESIST_WARRIOR,
	APPLY_RESIST_ASSASSIN,
	APPLY_RESIST_SURA,
	APPLY_RESIST_SHAMAN,
	APPLY_ENERGY,
	APPLY_DEF_GRADE,
	APPLY_COSTUME_ATTR_BONUS,
	APPLY_MAGIC_ATTBONUS_PER,
	APPLY_MELEE_MAGIC_ATTBONUS_PER,
	APPLY_RESIST_ICE,
	APPLY_RESIST_EARTH,
	APPLY_RESIST_DARK,
	APPLY_ANTI_CRITICAL_PCT,
	APPLY_ANTI_PENETRATE_PCT,
	APPLY_BLEEDING_REDUCE,
	APPLY_BLEEDING_PCT,
	APPLY_ATTBONUS_WOLFMAN,
	APPLY_RESIST_WOLFMAN,
	APPLY_RESIST_CLAW,
	APPLY_ACCEDRAIN_RATE,
	APPLY_RESIST_MAGIC_REDUCTION,
	APPLY_ENCHANT_ELECT,
	APPLY_ENCHANT_FIRE,
	APPLY_ENCHANT_ICE,
	APPLY_ENCHANT_WIND,
	APPLY_ENCHANT_EARTH,
	APPLY_ENCHANT_DARK,
	APPLY_ATTBONUS_CZ,
	APPLY_ATTBONUS_INSECT,
	APPLY_ATTBONUS_DESERT,
	APPLY_ATTBONUS_SWORD,
	APPLY_ATTBONUS_TWOHAND,
	APPLY_ATTBONUS_DAGGER,
	APPLY_ATTBONUS_BELL,
	APPLY_ATTBONUS_FAN,
	APPLY_ATTBONUS_BOW,
	APPLY_ATTBONUS_CLAW,
	APPLY_RESIST_HUMAN,
	APPLY_RESIST_MOUNT_FALL,
	APPLY_RESIST_FIST,
	APPLY_MOUNT,
	APPLY_SKILL_DAMAGE_SAMYEON,
	APPLY_SKILL_DAMAGE_TANHWAN,
	APPLY_SKILL_DAMAGE_PALBANG,
	APPLY_SKILL_DAMAGE_GIGONGCHAM,
	APPLY_SKILL_DAMAGE_GYOKSAN,
	APPLY_SKILL_DAMAGE_GEOMPUNG,
	APPLY_SKILL_DAMAGE_AMSEOP,
	APPLY_SKILL_DAMAGE_GUNGSIN,
	APPLY_SKILL_DAMAGE_CHARYUN,
	APPLY_SKILL_DAMAGE_SANGONG,
	APPLY_SKILL_DAMAGE_YEONSA,
	APPLY_SKILL_DAMAGE_KWANKYEOK,
	APPLY_SKILL_DAMAGE_GIGUNG,
	APPLY_SKILL_DAMAGE_HWAJO,
	APPLY_SKILL_DAMAGE_SWAERYUNG,
	APPLY_SKILL_DAMAGE_YONGKWON,
	APPLY_SKILL_DAMAGE_PABEOB,
	APPLY_SKILL_DAMAGE_MARYUNG,
	APPLY_SKILL_DAMAGE_HWAYEOMPOK,
	APPLY_SKILL_DAMAGE_MAHWAN,
	APPLY_SKILL_DAMAGE_BIPABU,
	APPLY_SKILL_DAMAGE_YONGBI,
	APPLY_SKILL_DAMAGE_PAERYONG,
	APPLY_SKILL_DAMAGE_NOEJEON,
	APPLY_SKILL_DAMAGE_BYEURAK,
	APPLY_SKILL_DAMAGE_CHAIN,
	APPLY_SKILL_DAMAGE_CHAYEOL,
	APPLY_SKILL_DAMAGE_SALPOONG,
	APPLY_SKILL_DAMAGE_GONGDAB,
	APPLY_SKILL_DAMAGE_PASWAE,
	APPLY_NORMAL_HIT_DEFEND_BONUS_BOSS_OR_MORE,
	APPLY_SKILL_DEFEND_BONUS_BOSS_OR_MORE,
	APPLY_NORMAL_HIT_DAMAGE_BONUS_BOSS_OR_MORE,
	APPLY_SKILL_DAMAGE_BONUS_BOSS_OR_MORE,
	APPLY_HIT_BUFF_ENCHANT_FIRE,
	APPLY_HIT_BUFF_ENCHANT_ICE,
	APPLY_HIT_BUFF_ENCHANT_ELEC,
	APPLY_HIT_BUFF_ENCHANT_WIND,
	APPLY_HIT_BUFF_ENCHANT_DARK,
	APPLY_HIT_BUFF_ENCHANT_EARTH,
	APPLY_HIT_BUFF_RESIST_FIRE,
	APPLY_HIT_BUFF_RESIST_ICE,
	APPLY_HIT_BUFF_RESIST_ELEC,
	APPLY_HIT_BUFF_RESIST_WIND,
	APPLY_HIT_BUFF_RESIST_DARK,
	APPLY_HIT_BUFF_RESIST_EARTH,
	APPLY_USE_SKILL_CHEONGRANG_MOV_SPEED,
	APPLY_USE_SKILL_CHEONGRANG_CASTING_SPEED,
	APPLY_USE_SKILL_CHAYEOL_CRITICAL_PCT,
	APPLY_USE_SKILL_SANGONG_ATT_GRADE_BONUS,
	APPLY_USE_SKILL_GIGUNG_ATT_GRADE_BONUS,
	APPLY_USE_SKILL_JEOKRANG_DEF_BONUS,
	APPLY_USE_SKILL_GWIGEOM_DEF_BONUS,
	APPLY_USE_SKILL_TERROR_ATT_GRADE_BONUS,
	APPLY_USE_SKILL_MUYEONG_ATT_GRADE_BONUS,
	APPLY_USE_SKILL_MANASHILED_CASTING_SPEED,
	APPLY_USE_SKILL_HOSIN_DEF_BONUS,
	APPLY_USE_SKILL_GICHEON_ATT_GRADE_BONUS,
	APPLY_USE_SKILL_JEONGEOP_ATT_GRADE_BONUS,
	APPLY_USE_SKILL_JEUNGRYEOK_DEF_BONUS,
	APPLY_USE_SKILL_GIHYEOL_ATT_GRADE_BONUS,
	APPLY_USE_SKILL_CHUNKEON_CASTING_SPEED,
	APPLY_USE_SKILL_NOEGEOM_ATT_GRADE_BONUS,
	APPLY_SKILL_DURATION_INCREASE_EUNHYUNG,
	APPLY_SKILL_DURATION_INCREASE_GYEONGGONG,
	APPLY_SKILL_DURATION_INCREASE_GEOMKYUNG,
	APPLY_SKILL_DURATION_INCREASE_JEOKRANG,
	APPLY_USE_SKILL_PALBANG_HP_ABSORB,
	APPLY_USE_SKILL_AMSEOP_HP_ABSORB,
	APPLY_USE_SKILL_YEONSA_HP_ABSORB,
	APPLY_USE_SKILL_YONGBI_HP_ABSORB,
	APPLY_USE_SKILL_CHAIN_HP_ABSORB,
	APPLY_USE_SKILL_PASWAE_SP_ABSORB,
	APPLY_USE_SKILL_GIGONGCHAM_STUN,
	APPLY_USE_SKILL_CHARYUN_STUN,
	APPLY_USE_SKILL_PABEOB_STUN,
	APPLY_USE_SKILL_MAHWAN_STUN,
	APPLY_USE_SKILL_GONGDAB_STUN,
	APPLY_USE_SKILL_SAMYEON_STUN,
	APPLY_USE_SKILL_GYOKSAN_KNOCKBACK,
	APPLY_USE_SKILL_SEOMJEON_KNOCKBACK,
	APPLY_USE_SKILL_SWAERYUNG_KNOCKBACK,
	APPLY_USE_SKILL_HWAYEOMPOK_KNOCKBACK,
	APPLY_USE_SKILL_GONGDAB_KNOCKBACK,
	APPLY_USE_SKILL_KWANKYEOK_KNOCKBACK,
	APPLY_USE_SKILL_SAMYEON_NEXT_COOLTIME_DECREASE_10PER,
	APPLY_USE_SKILL_GEOMPUNG_NEXT_COOLTIME_DECREASE_10PER,
	APPLY_USE_SKILL_GUNGSIN_NEXT_COOLTIME_DECREASE_10PER,
	APPLY_USE_SKILL_KWANKYEOK_NEXT_COOLTIME_DECREASE_10PER,
	APPLY_USE_SKILL_YONGKWON_NEXT_COOLTIME_DECREASE_10PER,
	APPLY_USE_SKILL_MARYUNG_NEXT_COOLTIME_DECREASE_10PER,
	APPLY_USE_SKILL_BIPABU_NEXT_COOLTIME_DECREASE_10PER,
	APPLY_USE_SKILL_NOEJEON_NEXT_COOLTIME_DECREASE_10PER,
	APPLY_USE_SKILL_SALPOONG_NEXT_COOLTIME_DECREASE_10PER,
	APPLY_USE_SKILL_PASWAE_NEXT_COOLTIME_DECREASE_10PER,
	APPLY_ATTBONUS_STONE,
	APPLY_DAMAGE_HP_RECOVERY,
	APPLY_DAMAGE_SP_RECOVERY,
	APPLY_ALIGNMENT_DAMAGE_BONUS,
	APPLY_NORMAL_DAMAGE_GUARD,
	APPLY_MORE_THEN_HP90_DAMAGE_REDUCE,
	APPLY_USE_SKILL_TUSOK_HP_ABSORB,
	APPLY_USE_SKILL_PAERYONG_HP_ABSORB,
	APPLY_USE_SKILL_BYEURAK_HP_ABSORB,
	APPLY_FIRST_ATTRIBUTE_BONUS,
	APPLY_SECOND_ATTRIBUTE_BONUS,
	APPLY_THIRD_ATTRIBUTE_BONUS,
	APPLY_FOURTH_ATTRIBUTE_BONUS,
	APPLY_FIFTH_ATTRIBUTE_BONUS,
	APPLY_USE_SKILL_SAMYEON_NEXT_COOLTIME_DECREASE_20PER,
	APPLY_USE_SKILL_GEOMPUNG_NEXT_COOLTIME_DECREASE_20PER,
	APPLY_USE_SKILL_GUNGSIN_NEXT_COOLTIME_DECREASE_20PER,
	APPLY_USE_SKILL_KWANKYEOK_NEXT_COOLTIME_DECREASE_20PER,
	APPLY_USE_SKILL_YONGKWON_NEXT_COOLTIME_DECREASE_20PER,
	APPLY_USE_SKILL_MARYUNG_NEXT_COOLTIME_DECREASE_20PER,
	APPLY_USE_SKILL_BIPABU_NEXT_COOLTIME_DECREASE_20PER,
	APPLY_USE_SKILL_NOEJEON_NEXT_COOLTIME_DECREASE_20PER,
	APPLY_USE_SKILL_SALPOONG_NEXT_COOLTIME_DECREASE_20PER,
	APPLY_USE_SKILL_PASWAE_NEXT_COOLTIME_DECREASE_20PER,
	APPLY_USE_SKILL_CHAYEOL_HP_ABSORB,
	APPLY_SUNGMA_STR,
	APPLY_SUNGMA_HP,
	APPLY_SUNGMA_MOVE,
	APPLY_SUNGMA_IMMUNE,
	APPLY_HIT_PCT,
	APPLY_RANDOM,
	APPLY_ATTBONUS_PER_HUMAN,
	APPLY_ATTBONUS_PER_ANIMAL,
	APPLY_ATTBONUS_PER_ORC,
	APPLY_ATTBONUS_PER_MILGYO,
	APPLY_ATTBONUS_PER_UNDEAD,
	APPLY_ATTBONUS_PER_DEVIL,
	APPLY_ENCHANT_PER_ELECT,
	APPLY_ENCHANT_PER_FIRE,
	APPLY_ENCHANT_PER_ICE,
	APPLY_ENCHANT_PER_WIND,
	APPLY_ENCHANT_PER_EARTH,
	APPLY_ENCHANT_PER_DARK,
	APPLY_ATTBONUS_PER_CZ,
	APPLY_ATTBONUS_PER_INSECT,
	APPLY_ATTBONUS_PER_DESERT,
	APPLY_ATTBONUS_PER_STONE,
	APPLY_ATTBONUS_PER_MONSTER,
	APPLY_RESIST_PER_HUMAN,
	APPLY_RESIST_PER_ICE,
	APPLY_RESIST_PER_DARK,
	APPLY_RESIST_PER_EARTH,
	APPLY_RESIST_PER_FIRE,
	APPLY_RESIST_PER_ELEC,
	APPLY_RESIST_PER_MAGIC,
	APPLY_RESIST_PER_WIND,
	APPLY_HIT_BUFF_SUNGMA_STR,
	APPLY_HIT_BUFF_SUNGMA_MOVE,
	APPLY_HIT_BUFF_SUNGMA_HP,
	APPLY_HIT_BUFF_SUNGMA_IMMUNE,
	APPLY_MOUNT_MELEE_MAGIC_ATTBONUS_PER,
	APPLY_DISMOUNT_MOVE_SPEED_BONUS_PER,
	APPLY_HIT_AUTO_HP_RECOVERY,
	APPLY_HIT_AUTO_SP_RECOVERY,
	APPLY_USE_SKILL_COOLTIME_DECREASE_ALL,
	APPLY_HIT_STONE_ATTBONUS_STONE,
	APPLY_HIT_STONE_DEF_GRADE_BONUS,
	APPLY_KILL_BOSS_ITEM_BONUS,
	APPLY_MOB_HIT_MOB_AGGRESSIVE,
	APPLY_NO_DEATH_AND_HP_RECOVERY30,
	APPLY_AUTO_PICKUP,
	APPLY_MOUNT_NO_KNOCKBACK,
	APPLY_SUNGMA_PER_STR,
	APPLY_SUNGMA_PER_HP,
	APPLY_SUNGMA_PER_MOVE,
	APPLY_SUNGMA_PER_IMMUNE,
	APPLY_IMMUNE_POISON100,
	APPLY_IMMUNE_BLEEDING100,
	APPLY_MONSTER_DEFEND_BONUS,
	APPLY_USE_SKILL_FINISH_NEXT_COOLTIME_DECREASE_PCT = 300,
	APPLY_USE_SKILL_ILGWANGPYO_NEXT_COOLTIME_DECREASE_PCT = 301,
	APPLY_USE_SKILL_PUNGLOEPO_NEXT_COOLTIME_DECREASE_PCT = 302,
	APPLY_USE_SKILL_GEOMAGGWI_NEXT_COOLTIME_DECREASE_PCT = 303,
	APPLY_USE_SKILL_MABEOBAGGWI_NEXT_COOLTIME_DECREASE_PCT = 304,
	APPLY_USE_SKILL_METEO_NEXT_COOLTIME_DECREASE_PCT = 305,
	APPLY_USE_SKILL_CHEONUN_NEXT_COOLTIME_DECREASE_PCT = 306,
	APPLY_USE_SKILL_ILIPUNGU_NEXT_COOLTIME_DECREASE_PCT = 307,
	APPLY_GLOVE_BASE_EFFECT_INCREASE = 308,
	APPLY_NO_FALLEN = 309,
	APPLY_HIT_AREA_ELEC_ATTACK = 310,
	APPLY_BLOCK_PENETRATE_PCT = 311,
	APPLY_ATTBONUS_MYSTERY_DUNGEON = 312,
	APPLY_ATTBONUS_DRAGON = 313,
	APPLY_CONFUSION_TO_MOB = 321,
	APPLY_ATTBONUS_MOON = 322,
	MAX_APPLY_NUM,
};

#pragma pack(push)
#pragma pack(1)
struct ItemLimit
{
	uint8_t type;
	long value;
};

struct ItemApply
{
	uint16_t type;
	long value;
};

struct ItemAddonRange
{
	uint32_t min;
	uint32_t max;
};

struct ItemProto
{
	uint32_t vnum;
	uint32_t vnum_range;

	char name[CHARACTER_NAME_MAX_LEN + 1];
	char locale_name[CHARACTER_NAME_MAX_LEN + 1];

	uint8_t type;
	uint8_t subtype;
	uint8_t weight;
	uint8_t size;

	uint32_t anti_flags;
	uint32_t flags;
	uint32_t wear_flags;
	uint32_t immune_flags;

	uint32_t shop_buy_price;
	uint32_t shop_sell_price;

	ItemLimit limits[ITEM_LIMIT_MAX_NUM];
	ItemApply applies[ITEM_APPLY_MAX_NUM];
	long values[ITEM_VALUES_MAX_NUM];
	long sockets[ITEM_SOCKET_MAX_NUM];

	uint32_t unknown_data2;
	uint32_t unknown_data3;

	uint32_t refined_vnum;
	uint16_t refine_set;
	uint32_t material67;

	uint8_t alter_to_magic_item_pct;
	uint8_t specular;
	uint8_t gain_socket_pct;
	//uint8_t addon_type;

	uint8_t mask_type;
	uint8_t mask_subtype;

public:
	std::string get_type_string() const;
	std::string get_subtype_string() const;

	std::string get_anti_flags_string() const;
	std::string get_flags_string() const;
	std::string get_wear_flags_string() const;
	std::string get_immune_flags_string() const;

	std::string get_limit_type_string(uint8_t index) const;
	long get_limit_type_value(uint8_t index) const;

	std::string get_apply_type_string(uint8_t index) const;
	long get_apply_type_value(uint8_t index) const;

	int8_t has_addon_type() const;
};
#pragma pack(pop)

using ItemProtoMap = std::map<uint32_t, ItemProto>;
